<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_webform_element_alter().
 *
 */
function my_custom_webform_element_alter(array &$element, FormStateInterface $form_state, array $context) {
  $stop=1;
  // check for desired element
  if (isset($element['#webform_id']) && $element['#webform_id'] === 'register--amount_of_vegetarians') {
    $element['#element_validate'][] = [
      'Drupal\my_custom\Validate\VegeConstraint',
      'validate'
    ];
  }
}

